name: mmmm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/ # 폴더 경로 지정

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.woff
